version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_NAME}
      - MYSQL_USER=${MARIADB_USERNAME}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
